name = "SheafSDP"
uuid = "b12ecbb7-bd40-4974-83b8-5680a8655045"
version = "0.1.0"
authors = ["Richard Samuelson <samuelson.rick@gmail.com>"]

[deps]
BlockSparseArrays = "719290be-2e67-4839-b464-1afd1c6ede3f"
CliqueTrees = "60701a23-6482-424a-84db-faee86b9b1f8"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[sources]
BlockSparseArrays = {path = "../BlockSparseArrays.jl"}
CliqueTrees = {path = "../CliqueTrees.jl"}

[compat]
CliqueTrees = "1.19.3"
Graphs = "1.14.0"
Krylov = "0.10.6"
LinearAlgebra = "1.12.0"
LinearOperators = "2.14.1"
SparseArrays = "1.12.0"
